name: Terraform Test

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  terraform-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        env:
          GITHUB_TOKEN: ${{ secrets.TERRAFORM_TEST_PAT_TOKEN }}
          GITHUB_OWNER: ${{ secrets.TERRAFORM_TEST_GITHUB_OWNER }}
          TF_VAR_github_username: ${{ secrets.TERRAFORM_TEST_GITHUB_USERNAME }}
          TF_VAR_github_email: ${{ secrets.TERRAFORM_TEST_GITHUB_EMAIL }}
        run: |
          terraform init
          terraform test -verbose
